// Cross-language golden test: load the corpus generated by the Rust unit
// test (`src-tauri/src/quick.rs::emit_cross_language_corpus`) and assert
// the browser-side parser produces the same `kind` for every entry.
//
// If this fails, one of the two implementations drifted:
//   - Rust changed: re-run `cargo test --lib quick::emit_cross_language_corpus`
//     to refresh `corpus.json`.
//   - TS changed: update `apps/web-spa/src/lib/quick/parse.ts` to match.
//   - Both changed on purpose: refresh CORPUS in the Rust test first.

import { describe, expect, it } from 'vitest';

import { parseQuick } from './parse';
import corpus from './corpus.json';

// 2026-08-17 10:00 local — same anchor used by `fn now()` in
// `src-tauri/src/quick.rs::tests`. Drift against wall clock would make
// "上周"/"明天" kind choices go the wrong way.
const NOW = new Date(2026, 7, 17, 10, 0, 0);

interface CorpusEntry {
  text: string;
  kind: string;
}

describe('quick parser — cross-language corpus', () => {
  for (const entry of corpus as CorpusEntry[]) {
    it(`"${entry.text}" → ${entry.kind}`, () => {
      const r = parseQuick(entry.text, { now: NOW });
      expect(r.kind).toBe(entry.kind);
    });
  }
});